import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import formImage from "../public/form.png";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion } from "framer-motion";

export default function Home() {
  /* Router */
  const router = useRouter();

  /* formik logic */
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "India",
      terms: "",
    },

    /* Validation from yup */
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 10 characters or less")
        .required("Name is Required")
        .matches(/^[aA-zZ\s]+$/, "Only alphabets are allowed for this field "),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required")
        .matches(
          /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/,
          "Enter valid email address"
        ),
      terms: Yup.array().required("Term is must checked to continue"),
    }),

    /* Submit form */
    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  /* const [name, setName] = useState(""); */
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <Head>
        <title>Modern React Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center mx-auto">
        <form
          className="bg-white flex rounded-lg w-auto"
          onSubmit={formik.handleSubmit}
        >
          {/* for form type content */}
          <div className="flex flex-wrap flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-serif">Lets get started</h1>
            <p className="text-lg text-gray-500">
              Join our e-learing platform today and see what we got for you
            </p>
            <div className="mt-6">
              {/* name input field */}
              <div className="pb-4">
                <label
                  className={`block font-sans text-sm pb-2 font-semibold 
                  ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-600"
                      : ""
                  }`}
                  htmlFor="name"
                >
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name"}
                </label>
                <input
                  className={`w-2/3 border-2 border-gray-500 p-2 rounded-md focus:border-teal-500 focus:ring-teal-500 
                  ${
                    formik.touched.name && formik.errors.name
                      ? "border-red-600"
                      : ""
                  }`}
                  type="text"
                  name="name"
                  placeholder="Enter your name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* email input field */}
              <div className="pb-4">
                <label
                  className={`block font-sans text-sm pb-2 font-semibold 
                  ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-600"
                      : ""
                  }`}
                  htmlFor="email"
                >
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>
                <input
                  className={`w-2/3 border-2 border-gray-500 p-2 rounded-md focus:border-teal-500 focus:ring-teal-500 
                  ${
                    formik.touched.email && formik.errors.email
                      ? "border-red-600"
                      : ""
                  } `}
                  type="email"
                  name="email"
                  placeholder="Enter your email"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* Country input field */}
              <div className="pb-4">
                <label
                  className="block font-sans text-sm pb-2 font-semibold"
                  htmlFor="country"
                >
                  Country
                </label>
                <select
                  name="country"
                  className="w-2/3 border-2 border-gray-500 p-2 rounded-md focus:border-teal-500 focus:ring-teal-500"
                >
                  <option value="">US</option>
                  <option value="">UK</option>
                  <option value="">Germany</option>
                  <option value="">India</option>
                </select>
              </div>

              {/* terms of services */}
              <div className="pb-4">
                <label
                  htmlFor="terms"
                  className={`block font-sans text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-600"
                      : ""
                  }`}
                >
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms of services"}
                </label>
                <div className="flex items-center gap-2">
                  <input
                    className={`h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500 cursor-pointer 
                    ${
                      formik.touched.terms && formik.errors.terms
                        ? "border-red-600"
                        : ""
                    }`}
                    type="checkbox"
                    name="terms"
                    value="checked"
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                  />
                  <p className="text-sm font-serif text-gray-400">
                    I agree to the Terms and Service that my data will be taken
                  </p>
                </div>
              </div>

              {/* Button */}
              <button className="bg-teal-500 font-serif text-sm text-white py-3 mt-6 rounded-lg w-full ">
                Start learing
              </button>
            </div>
          </div>

          {/* Image */}
          <div className="relative flex-1">
            <Image
              className=" object-cover rounded-lg"
              fill
              priority
              src={formImage}
              alt="form-learn"
            />
          </div>
        </form>
      </main>
    </motion.div>
  );
}
